# Title of site, shows up in tab title
name: Math Mondays

# Short bio or description, shows up in tab title
description: It's a work in progress

# Your website URL, used for Sitemap.xml and your RSS feed
url: http://mathmondays.com

# blank for user pages, non-empty for project pages
baseurl: ""

# ???
version: v3.6.2

# Show errors if front matter is invalid
strict_front_matter: true

# Determines how much of a post to show on the front page
excerpt_separator: <!--more-->

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: HenrySwanson
  instagram:
  linkedin:
  pinterest:
  rss: 1
  twitter:
  stackoverflow: users/2216552/henry-swanson
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Defines the URL for a page/post
permalink: /:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  # Can minify by using :compressed
  style: :expanded

# Use the following plug-ins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - package-lock.json
