name: Build and Deploy Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push events only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job called "build" and one called "deploy"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Node
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node packages
        run: |
          cd asset-generator && npm install --save-dev

      - name: Clear asset directory
        run: |
          rm -Rf content/images
          rm -Rf content/js

      - name: Generate dynamic assets
        run: |
          cd asset-generator
          rm -Rf dist web-bundles
          tsc
          node dist/index.js
          webpack --mode production

      - name: Copy dynamic assets into the site directory
        run: |
          cp -r asset-generator/static/. content/images
          cp -r asset-generator/web-bundles/. content/js

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build site
        run: |
          pelican content -o output -s publishconf.py

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # upload just the output folder
          path: './output'

  # The deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
