# This is a basic workflow to help you get started with Actions

name: Build Pelican Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push events only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # THIS IS A BAD HACK, DELETE WHEN POSSIBLE
      - name: patch in a fix for summary plugin
        run: |
           MODULE_PATH=$(
               pip show minchin.pelican.plugins.summary | \
               grep 'Location:' | \
               awk '{print $2}'
           )
           FILE_PATH=$MODULE_PATH/minchin/pelican/plugins/summary/summary.py
           sed -i 's/instance._summary/instance.metadata["summary"]/' $FILE_PATH

      - name: Build site
        run: |
          pelican content -o output -s publishconf.py
          
      - name: Commit to gh-pages branch
        run: |
          ghp-import output -b gh-pages
          git push -f origin gh-pages
