# Responsible for building and deploying the static pages that make up
# the website.
name: Build and Deploy Site

# Controls when the action will run. 
on:
  # Triggers the workflow on push events only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      - name: Install just
        run: sudo apt install just

      # Set up Node
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version-file: asset-generator/.nvmrc

      - name: Install Node packages
        run: |
          cd asset-generator && npm ci

      - name: Run tests
        run: just test

      - name: Generate assets
        run: just assets

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"     

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install Python dependencies
        run: uv sync --locked

      - name: Build site
        run: |
          uv run pelican content -o output -s publishconf.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # upload just the output folder
          path: './output'

  # The deploy job
  deploy:
    runs-on: ubuntu-latest
    # Only deploy if this commit was to master
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
